dist: trusty
sudo: require
language: cpp
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
before_install:
    - gcc -v && g++ -v
    - doxygen docs/Doxyfile

deploy_docs:
  provider: pages
  skip_cleanup: pages
  github-token: $GH_REPO_TOKEN # Set in the settings page of your repository, as a secure variable
  local_dir: docs/html
  on:
    branch: master

script:
    - mkdir BuildNebula
    - cd BuildNebula
    - export WORK_PATH=`pwd`
    - mkdir NebulaDepend NebulaDependBuild
    - cd NebulaDependBuild
    - wget https://github.com/google/protobuf/archive/v3.6.0.zip
    - unzip v3.6.0.zip
    - cd protobuf-3.6.0
    - chmod u+x autogen.sh
    - ./autogen.sh
    - ./configure --prefix=${WORK_PATH}/NebulaDepend
    - make
    - make install
    - cd ..
    - git clone https://github.com/kindy/libev.git libev
    - cd libev/src
    - chmod u+x autogen.sh
    - ./autogen.sh
    - ./configure --prefix=${WORK_PATH}/NebulaDepend
    - make
    - make install
    - cd ../../
    - git clone https://github.com/redis/hiredis.git hiredis
    - cd hiredis
    - make
    - mkdir ../../NebulaDepend/include/hiredis
    - cp -r adapters *.h ../../NebulaDepend/include/hiredis/
    - cp libhiredis.so ../../NebulaDepend/lib/
    - cd ..
    - wget https://github.com/weidai11/cryptopp/archive/CRYPTOPP_6_0_0.tar.gz
    - tar -zxvf CRYPTOPP_6_0_0.tar.gz
    - cd cryptopp-CRYPTOPP_6_0_0
    - make libcryptopp.so
    - mkdir ../../NebulaDepend/include/cryptopp
    - cp *.h ../../NebulaDepend/include/cryptopp/
    - cp libcryptopp.so ../../NebulaDepend/lib/
    - cd ..
    - wget https://github.com/openssl/openssl/archive/OpenSSL_1_1_0.zip
    - unzip OpenSSL_1_1_0.zip
    - rm OpenSSL_1_1_0.zip 
    - cd openssl-OpenSSL_1_1_0
    - ./config --prefix=${WORK_PATH}/NebulaDepend
    - make
    - make install
    - cd ..

    # now build nebula
    - cd ..
    - git clone https://github.com/Bwar/Nebula.git Nebula
    - mkdir Nebula/include
    - mkdir Nebula/lib
    - cd Nebula/proto
    - ${WORK_PATH}/NebulaDepend/bin/protoc *.proto --cpp_out=../src/pb
    - cd ../src
    - make
